### PR TITLE
Actually use project variable in download script

### LINKED ISSUE #308: Latest stable build script incorrect
in the script showed [here](https://docs.papermc.io/misc/downloads-api#downloading-latest-stable-build) it asks for a `project` entry but uses it only once and does not implement it in the way that it could support all projects.

this is the script listed on the docs:
```sh
#!/bin/bash

PROJECT="paper"
MINECRAFT_VERSION="1.20.4"

LATEST_VERSION=$(curl -s https://api.papermc.io/v2/projects/paper | \
    jq -r '.versions[-1]')

LATEST_BUILD=$(curl -s https://api.papermc.io/v2/projects/${PROJECT}/versions/${MINECRAFT_VERSION}/builds | \
    jq -r '.builds | map(select(.channel == "default") | .build) | .[-1]')

JAR_NAME=paper-${LATEST_VERSION}-${LATEST_BUILD}.jar

PAPERMC_URL="https://api.papermc.io/v2/projects/paper/versions/${LATEST_VERSION}/builds/${LATEST_BUILD}/downloads/${JAR_NAME}"

# Download the latest PaperMC version
curl -o server.jar $PAPERMC_URL
echo "Downloads completed"
```

Let me list the flaws
1.  line 5: `LATEST_VERSION=$(curl -s https://api.papermc.io/v2/projects/paper | \` the url is hardcoded to the paper project
2. line 12: `JAR_NAME=paper-${LATEST_VERSION}-${LATEST_BUILD}.jar` the filename is hardcoded to the paper project
3. line 14: `PAPERMC_URL="https://api.papermc.io/v2/projects/paper/versions/${LATEST_VERSION}/builds/${LATEST_BUILD}/downloads/${JAR_NAME}"` the url is hardcoded to the paper project.

This is a slightly modified version of the script that does support all projects and does not hard code any projects into the script
```sh
#!/bin/bash

PROJECT="paper"
MINECRAFT_VERSION="1.20.4"

LATEST_VERSION=$(curl -s https://api.papermc.io/v2/projects/${PROJECT} | \
    jq -r '.versions[-1]')

LATEST_BUILD=$(curl -s https://api.papermc.io/v2/projects/${PROJECT}/versions/${MINECRAFT_VERSION}/builds | \
    jq -r '.builds | map(select(.channel == "default") | .build) | .[-1]')

JAR_NAME=${PROJECT}-${LATEST_VERSION}-${LATEST_BUILD}.jar

PAPERMC_URL="https://api.papermc.io/v2/projects/${PROJECT}/versions/${LATEST_VERSION}/builds/${LATEST_BUILD}/downloads/${JAR_NAME}"

# Download the latest PaperMC version
curl -o server.jar $PAPERMC_URL
echo "Downloads completed"
```

### PR DESCRIPTION
**Pull request by Leguan16**
fixes #308 

@phant0m2290 if you want me to add you as co-author i would need your commit signature

### CODE REVIEW

**Comment by phant0m2290** [comment]
> fixes #308
> 
> @phant0m2290 if you want me to add you as co-author i would need your commit signature

how do i do that?

**Review by zlataovce — APPROVED** [review]

**Comment by Leguan16** [comment]
> > fixes #308
> 
> > 
> 
> > @phant0m2290 if you want me to add you as co-author i would need your commit signature
> 
> 
> 
> how do i do that? or what is that? @Leguan16 

The email and user you provide to commit something to a git repo.

**Comment by phant0m2290** [comment]
> > > fixes #308
> > 
> > 
> > > 
> > 
> > 
> > > @phant0m2290 if you want me to add you as co-author i would need your commit signature
> > 
> > 
> > how do i do that? or what is that? @Leguan16
> 
> The email and user you provide to commit something to a git repo.

Ahh alr
user: phant0m2290
email: titulaerkay@gmail.com

**Comment by Leguan16** [comment]
done.

> > > > fixes #308
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > @phant0m2290 if you want me to add you as co-author i would need your commit signature
> > > 
> > > 
> > > how do i do that? or what is that? @Leguan16
> > 
> > 
> > The email and user you provide to commit something to a git repo.
> 
> Ahh alr user: phant0m2290 email: [titulaerkay@gmail.com](mailto:titulaerkay@gmail.com)

done

**Review by olijeffers0n — APPROVED** [review]

**Pull request merged**
