### PR TITLE
separate config specs into other files

### PR DESCRIPTION
**Pull request by Machine-Maker**
I think its best if the specs for the various configs are loaded from a separate file instead of inline. Gives benefits when editing the yml directly in editors and prepares for a time from when the specs are read from the web instead of hardcoded.

```[tasklist]
- [x] server.properties
- [x] spigot.yml
- [x] bukkit.yml
- [x] paper-global.yml
- [x] paper-world-defaults.yml
```

### CODE REVIEW

**Comment by olijeffers0n** [comment]
Looks like a good start, the only thing I was wondering was if we wanted to maybe place the YML files within a subdirectory like we do with assets? Other than that this should be good

**Comment by MiniDigger** [comment]
> prepares for a time from when the specs are read from the web
maybe we should define them as a json schema then?

**Comment by Machine-Maker** [comment]
> Looks like a good start, the only thing I was wondering was if we wanted to maybe place the YML files within a subdirectory like we do with assets?

Yeah, we could do that. Probably doesn't have to be in the `docs/` directory

**Comment by olijeffers0n** [comment]
Is there anything making this not ready for review?

**Review by olijeffers0n — APPROVED** [review]

**Pull request merged**
