### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by powercasgamer**

### CODE REVIEW

**Comment by RiddickPower** [comment]
merge asap

**Comment by dawon** [comment]
Maybe add [ci skip] to PR name?

**Review by e-im — APPROVED** [review]
whoops, thanks!


ci-skip does not do anything here. There are no published, downloadable builds of docs available.

**Comment by dawon** [comment]
> whoops, thanks!
> 
> ci-skip does not do anything here. There are no published, downloadable builds of docs available.

Ah, my bad, sorry :/

**Pull request merged**
