### PR TITLE
Add docs for player reloot time

### PR DESCRIPTION
**Pull request by Machine-Maker**

### CODE REVIEW

**Comment by olijeffers0n** [comment]
What’s the unit?

**Comment by lynxplay** [comment]
> What’s the unit?

The duration, supports s,m,h,d.

**Comment by olijeffers0n** [comment]
Should it maybe say that? From a quick look at paper it seems like only one unit is permitted rather than 2h3m30s which is how I would use this.

**Comment by lynxplay** [comment]
Probably yea :+1:

**Review by olijeffers0n — APPROVED** [review]

**Pull request merged**
