### PR TITLE
Update Docusaurus to v3

### PR DESCRIPTION
**Pull request by olijeffers0n**
Docusaurus v3 has been released bringing some slight Markdown changes. Namely, curly braces may need escaping within markdown and <! -- --> comments are not supported

### CODE REVIEW

**Comment by olijeffers0n** [comment]
I have done some looking through the deployment and I believe everything is alright. If anyone can have a look through that would be appreciated :smile:

**Comment by e-im** [comment]
3.0 is [out now](https://github.com/facebook/docusaurus/releases/tag/v3.0.0). Looking at the changes between this pr and the actual release it should just be a matter of updating the packages.

The primary change is an update from MDX v2 to the newly released [MDX 3](https://mdxjs.com/blog/v3/)

This sounds pretty major (i.e. v1 -> v2), but its actually just a few very small changes, hence why it was added at the very end. We don't inferface with MDX directly hence no changes are needed. It's only [new features](https://mdxjs.com/blog/v3/#improvements-to-the-mdx-format)

**Comment by olijeffers0n** [comment]
Yep! Got the notification too. I marked it as draft when the RC came out. I’ll be looking to update in the coming days around Uni work. Someone poke me if i forget 😝

**Comment by e-im** [comment]
I had missed this initially but the patch for `@docusaurus/core` can also now be removed because loading typescript config files is now natively supported https://github.com/facebook/docusaurus/pull/9317

**Comment by olijeffers0n** [comment]
Okey, all patches are updated. Ready for reviewal

**Review by powercasgamer — CHANGES_REQUESTED** [review]
The [Internationalization](https://docs.papermc.io/paper/dev/component-api/i18n) page should probably also be added to Velocity

**Review by Machine-Maker — APPROVED** [review]

**Pull request merged**
