### PR TITLE
Document side effect of disable-ice-and-snow

### PR DESCRIPTION
**Pull request by NoahvdAa**
Noticed this while researching PaperMC/Paper#7605.

### CODE REVIEW

**Comment by Owen1212055** [comment]
I assume this also effects them being able to be filled up by snow as well?

**Comment by Machine-Maker** [comment]
how long has rain filled up cauldrons? does this config pre-date that? if so, I feel like the solution is to make that config *not* affect this.

**Comment by NoahvdAa** [comment]
According to [the Minecraft wiki](https://minecraft.fandom.com/wiki/Cauldron), rain filling cauldrons was added in Minecraft 1.3.1.

**Comment by Machine-Maker** [comment]
k, that's a lot older than I thought. guess it can stay. just seems weird 🤷

**Review by sulu5890 — APPROVED** [review]

**Pull request merged**
